### ISSUE TITLE
Add PHP nightly builds to continuous integration tests

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#188]
```yml
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - bash tests/before_script.sh

script:
  - bash tests/script.sh
```
