### ISSUE TITLE
Add PHP 5.3 to tests

### ISSUE THREAD

**Issue by zborboa-g** [php-curl-class/php-curl-class#34]
Add PHP 5.3 to tests for syntax checking, but exclude it from the phpunit tests as the built-in development server is only available >= 5.4.0.

``` yml
language: php
php:
  - 5.3
script:
  - php -l src/Curl.class.php
  - if [[ "$TRAVIS_PHP_VERSION" != "5.3" ]]; then
      cd tests && phpunit --configuration phpunit.xml
    fi
```
