### ISSUE TITLE
Add hhvm to tests

### ISSUE THREAD

**Issue by zborboa-g** [php-curl-class/php-curl-class#35]
Add hhvm to tests.

``` yml
language: php
php:
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
```
