### ISSUE TITLE
Add PHP 7.3 to continuous integration tests

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#560]
https://secure.php.net/ChangeLog-7.php#7.3.0
https://wiki.php.net/todo/php73
https://secure.php.net/supported-versions.php

```
matrix:
  include:
    - php: 7.3
      dist: trusty
```
